import { useState, useEffect } from 'react';
import { supabase } from '../lib/supabase';
import RevenueChart from '../components/RevenueChart';
import { CheckCircle, AlertCircle, X, ChevronRight } from 'lucide-react';

export default function Subscriptions() {
  const [activeTab, setActiveTab] = useState<'student' | 'teacher'>('teacher');
  const [teacherStats, setTeacherStats] = useState<any[]>([]);
  const [profiles, setProfiles] = useState<Record<string, any>>({});
  const [loading, setLoading] = useState(true);

  // Stats
  const [totalGrossRevenue, setTotalGrossRevenue] = useState(0);
  const [totalTeacherShare, setTotalTeacherShare] = useState(0);
  const [totalPendingPayouts, setTotalPendingPayouts] = useState(0);

  // Student Billing Modal State
  const [selectedStudent, setSelectedStudent] = useState<any | null>(null);

  // Mock Data for Students
  const mockStudents = [
    {
      id: 's1',
      name: 'John Doe',
      email: 'john.doe@school.com',
      status: 'Active',
      subscriptions: [
        { course: 'O-Level Mathematics', teacher: 'Mr. Takunda', price: 15.00 },
        { course: 'Combined Science', teacher: 'Mrs. Chipo', price: 10.00 }
      ]
    },
    {
      id: 's2',
      name: 'Sarah Moyo',
      email: 'sarah.m@gmail.com',
      status: 'Active',
      subscriptions: [
        { course: 'A-Level History', teacher: 'Dr. Sarah', price: 20.00 }
      ]
    },
    {
      id: 's3',
      name: 'Tendai Ndlovu',
      email: 'tendai@gmail.com',
      status: 'Past Due',
      subscriptions: [
        { course: 'O-Level Mathematics', teacher: 'Mr. Takunda', price: 15.00 }
      ]
    }
  ];

  const fetchPayoutData = async () => {
    setLoading(true);
    try {
      // 1. Fetch teacher stats
      const { data: statsData, error: statsError } = await supabase
        .from('teacher_stats')
        .select('*');

      if (statsError) throw statsError;

      // 2. Fetch profiles for those teachers
      const teacherIds = statsData?.map(s => s.teacher_id) || [];
      const { data: profilesData } = await supabase
        .from('profiles')
        .select('id, full_name, email')
        .in('id', teacherIds);

      const profileMap: Record<string, any> = {};
      profilesData?.forEach(p => {
        profileMap[p.id] = p;
      });

      let stats = statsData || [];
      let mappedProfiles = profileMap;

      // Fallback to mock data for demonstration if DB is empty
      if (stats.length === 0) {
        stats = [
          { id: '1', teacher_id: 't1', total_revenue: 1200.00, pending_payout: 350.00, total_students: 45 },
          { id: '2', teacher_id: 't2', total_revenue: 850.50, pending_payout: 120.00, total_students: 32 },
          { id: '3', teacher_id: 't3', total_revenue: 450.00, pending_payout: 0.00, total_students: 15 }
        ];
        mappedProfiles = {
          't1': { full_name: 'Mrs. Chipo', email: 'chipo@mentora.com' },
          't2': { full_name: 'Mr. Takunda', email: 'takunda@mentora.com' },
          't3': { full_name: 'Dr. Sarah', email: 'sarah@mentora.com' }
        };
      }

      setProfiles(mappedProfiles);
      setTeacherStats(stats);

      // Calculate totals
      let gross = 0;
      let teacherShare = 0;
      let pending = 0;
      stats.forEach((stat: any) => {
        gross += Number(stat.total_revenue) || 0;
        // Assuming the total_revenue stored in stats is the GROSS revenue generated by that teacher.
        // Wait, if teacher_stats.total_revenue is their share or gross? Let's assume it's gross.
        // We will calculate 75% of gross as their share, OR assume pending_payout is what we owe them.
        // Let's sum up total_revenue as gross.
        teacherShare += (Number(stat.total_revenue) || 0) * 0.75;
        pending += Number(stat.pending_payout) || 0;
      });
      setTotalGrossRevenue(gross);
      setTotalTeacherShare(teacherShare);
      setTotalPendingPayouts(pending);

    } catch (error) {
      console.error('Error fetching payout data:', error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (activeTab === 'teacher') {
      fetchPayoutData();
    }
  }, [activeTab]);

  const handleApprovePayout = async (statId: string, teacherName: string, amount: number) => {
    if (amount <= 0) {
      alert('Nothing to pay out.');
      return;
    }
    const confirmed = window.confirm(`Are you sure you want to approve a payout of $${amount.toFixed(2)} to ${teacherName}?`);
    if (!confirmed) return;

    try {
      if (statId.length > 5) {
        // Only attempt DB update if it's a real UUID, not our mock data ('1', '2', '3')
        const { error } = await supabase
          .from('teacher_stats')
          .update({ pending_payout: 0 })
          .eq('id', statId);

        if (error) throw error;
      }
      
      // Update local state
      setTeacherStats(prev => prev.map(stat => 
        stat.id === statId ? { ...stat, pending_payout: 0 } : stat
      ));
      setTotalPendingPayouts(prev => Math.max(0, prev - amount));
      
      alert(`Successfully processed payout for ${teacherName}`);
    } catch (err) {
      console.error('Error processing payout:', err);
      alert('Failed to process payout. Check console for details.');
    }
  };

  return (
    <div className="max-w-7xl mx-auto space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold text-text">Finance & Payouts</h1>
        <p className="text-textMuted mt-2">Manage student billing and teacher revenue splitting.</p>
      </div>

      {/* Tabs */}
      <div className="flex space-x-1 bg-surface p-1 rounded-2xl border border-border w-fit">
        <button
          onClick={() => setActiveTab('student')}
          className={`px-4 py-2 rounded-2xl font-medium text-sm transition-colors ${
            activeTab === 'student' ? 'bg-background text-text ' : 'text-textMuted hover:text-text'
          }`}
        >
          Student Billing
        </button>
        <button
          onClick={() => setActiveTab('teacher')}
          className={`px-4 py-2 rounded-2xl font-medium text-sm transition-colors ${
            activeTab === 'teacher' ? 'bg-background text-text ' : 'text-textMuted hover:text-text'
          }`}
        >
          Teacher Payouts
        </button>
      </div>

      {activeTab === 'student' && (
        <div className="mt-6">
          <div className="bg-surface border border-border rounded-3xl overflow-hidden">
            <div className="p-4 border-b border-border flex justify-between items-center">
              <h3 className="font-bold text-text text-lg">Active Student Subscriptions</h3>
            </div>
            
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="bg-background border-b border-border text-textMuted text-sm">
                    <th className="p-4 font-medium">Student</th>
                    <th className="p-4 font-medium text-center">Active Subscriptions</th>
                    <th className="p-4 font-medium">Total Monthly Payment</th>
                    <th className="p-4 font-medium">Status</th>
                    <th className="p-4 font-medium text-right">Details</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border">
                  {mockStudents.map((student) => {
                    const totalPayment = student.subscriptions.reduce((sum, sub) => sum + sub.price, 0);
                    return (
                      <tr 
                        key={student.id} 
                        className="hover:bg-background transition-colors cursor-pointer"
                        onClick={() => setSelectedStudent(student)}
                      >
                        <td className="p-4">
                          <div className="font-medium text-text">{student.name}</div>
                          <div className="text-xs text-textMuted">{student.email}</div>
                        </td>
                        <td className="p-4 text-center">
                          <span className="bg-surface border border-border text-text px-2 py-1 rounded-2xl text-sm font-medium">
                            {student.subscriptions.length} Courses
                          </span>
                        </td>
                        <td className="p-4 font-medium text-text">${totalPayment.toFixed(2)}</td>
                        <td className="p-4">
                          <span className={`px-2 py-1 text-xs rounded-full font-medium ${
                            student.status === 'Active' ? 'bg-success/10 text-success' : 'bg-orange-500/10 text-orange-500'
                          }`}>
                            {student.status}
                          </span>
                        </td>
                        <td className="p-4 text-right">
                          <ChevronRight className="w-5 h-5 text-textMuted inline-block" />
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}

      {/* Student Details Modal */}
      {selectedStudent && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/90  p-4" onClick={() => setSelectedStudent(null)}>
          <div className="bg-surface border border-border rounded-3xl w-full max-w-2xl overflow-hidden " onClick={e => e.stopPropagation()}>
            <div className="p-6 border-b border-border flex justify-between items-start">
              <div>
                <h2 className="text-2xl font-bold text-text">{selectedStudent.name}</h2>
                <p className="text-textMuted">{selectedStudent.email}</p>
              </div>
              <button onClick={() => setSelectedStudent(null)} className="p-2 hover:bg-background rounded-2xl text-textMuted transition-colors">
                <X className="w-5 h-5" />
              </button>
            </div>
            
            <div className="p-6">
              <div className="flex justify-between items-center mb-6">
                <h3 className="text-lg font-bold text-text">Subscription Breakdown</h3>
                <span className={`px-3 py-1 text-sm rounded-full font-medium ${
                  selectedStudent.status === 'Active' ? 'bg-success/10 text-success' : 'bg-orange-500/10 text-orange-500'
                }`}>
                  Account {selectedStudent.status}
                </span>
              </div>
              
              <div className="border border-border rounded-3xl overflow-hidden">
                <table className="w-full text-left border-collapse">
                  <thead>
                    <tr className="bg-background border-b border-border text-textMuted text-sm">
                      <th className="p-4 font-medium">Course</th>
                      <th className="p-4 font-medium">Teacher</th>
                      <th className="p-4 font-medium text-right">Price</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-border">
                    {selectedStudent.subscriptions.map((sub: any, idx: number) => (
                      <tr key={idx} className="hover:bg-background transition-colors">
                        <td className="p-4 font-medium text-text">{sub.course}</td>
                        <td className="p-4 text-textMuted">{sub.teacher}</td>
                        <td className="p-4 text-right text-textMuted">${sub.price.toFixed(2)}</td>
                      </tr>
                    ))}
                  </tbody>
                  <tfoot className="bg-background border-t border-border">
                    <tr>
                      <td colSpan={2} className="p-4 font-bold text-right text-text">Total Monthly:</td>
                      <td className="p-4 font-bold text-right text-text text-lg">
                        ${selectedStudent.subscriptions.reduce((sum: number, sub: any) => sum + sub.price, 0).toFixed(2)}
                      </td>
                    </tr>
                  </tfoot>
                </table>
              </div>
            </div>
          </div>
        </div>
      )}

      {activeTab === 'teacher' && (
        <div className="mt-6">
          <RevenueChart 
            totalRevenue={totalGrossRevenue} 
            teacherShare={totalTeacherShare} 
            platformShare={totalGrossRevenue - totalTeacherShare} 
            totalPending={totalPendingPayouts}
          />

          <div className="bg-surface border border-border rounded-3xl overflow-hidden">
            <div className="p-4 border-b border-border flex justify-between items-center">
              <h3 className="font-bold text-text text-lg">Pending Payouts</h3>
            </div>
            
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="bg-background border-b border-border text-textMuted text-sm">
                    <th className="p-4 font-medium">Teacher</th>
                    <th className="p-4 font-medium">Total Students</th>
                    <th className="p-4 font-medium">Lifetime Revenue</th>
                    <th className="p-4 font-medium">Pending Payout (75%)</th>
                    <th className="p-4 font-medium text-right">Action</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border">
                  {loading ? (
                    <tr>
                      <td colSpan={5} className="p-8 text-center text-textMuted">Loading payouts...</td>
                    </tr>
                  ) : teacherStats.length === 0 ? (
                    <tr>
                      <td colSpan={5} className="p-8 text-center text-textMuted">No teacher stats found.</td>
                    </tr>
                  ) : (
                    teacherStats.map((stat) => {
                      const profile = profiles[stat.teacher_id] || {};
                      const teacherName = profile.full_name || profile.email || 'Unknown Teacher';
                      const pendingPayout = Number(stat.pending_payout) || 0;
                      
                      return (
                        <tr key={stat.id} className="hover:bg-background transition-colors">
                          <td className="p-4">
                            <div className="font-medium text-text">{teacherName}</div>
                            <div className="text-xs text-textMuted">{stat.teacher_id}</div>
                          </td>
                          <td className="p-4 text-textMuted">{stat.total_students}</td>
                          <td className="p-4 text-textMuted">${Number(stat.total_revenue || 0).toFixed(2)}</td>
                          <td className="p-4">
                            <span className={`font-bold ${pendingPayout > 0 ? 'text-success' : 'text-textMuted'}`}>
                              ${pendingPayout.toFixed(2)}
                            </span>
                          </td>
                          <td className="p-4 text-right">
                            {pendingPayout > 0 ? (
                              <button 
                                onClick={() => handleApprovePayout(stat.id, teacherName, pendingPayout)}
                                className="flex items-center space-x-1 bg-success hover:bg-success/90 text-white px-3 py-1.5 rounded-2xl text-sm font-medium transition-colors ml-auto"
                              >
                                <CheckCircle className="w-4 h-4" />
                                <span>Approve</span>
                              </button>
                            ) : (
                              <div className="flex items-center space-x-1 text-textMuted text-sm justify-end">
                                <AlertCircle className="w-4 h-4" />
                                <span>Settled</span>
                              </div>
                            )}
                          </td>
                        </tr>
                      );
                    })
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
