DELETE FROM courses WHERE id LIKE 'zimsec-%';
INSERT INTO courses (id, title, board, level, syllabus_code, subject_category, status, icon, color) VALUES
('zimsec-g1-english', 'Grade 1 English', 'ZIMSEC', 'Grade 1', 'N/A', 'Languages', 'active', 'BookOpen', 'bg-blue-500'),
('zimsec-g1-math', 'Grade 1 Mathematics', 'ZIMSEC', 'Grade 1', 'N/A', 'Mathematics', 'active', 'Calculator', 'bg-red-500'),
('zimsec-g1-shona', 'Grade 1 Shona', 'ZIMSEC', 'Grade 1', 'N/A', 'Languages', 'active', 'BookOpen', 'bg-blue-600'),
('zimsec-g1-ndebele', 'Grade 1 Ndebele', 'ZIMSEC', 'Grade 1', 'N/A', 'Languages', 'active', 'BookOpen', 'bg-blue-600'),
('zimsec-g1-agriculture', 'Grade 1 Agriculture', 'ZIMSEC', 'Grade 1', 'N/A', 'Sciences', 'active', 'Sprout', 'bg-green-600'),
('zimsec-g1-scitech', 'Grade 1 Science and Technology', 'ZIMSEC', 'Grade 1', 'N/A', 'Sciences', 'active', 'FlaskConical', 'bg-green-500'),
('zimsec-g1-heritage', 'Grade 1 Heritage - Social Studies', 'ZIMSEC', 'Grade 1', 'N/A', 'Humanities', 'active', 'Landmark', 'bg-amber-600'),
('zimsec-g1-fareme', 'Grade 1 FAREME', 'ZIMSEC', 'Grade 1', 'N/A', 'Humanities', 'active', 'Users', 'bg-orange-500'),
('zimsec-g2-english', 'Grade 2 English', 'ZIMSEC', 'Grade 2', 'N/A', 'Languages', 'active', 'BookOpen', 'bg-blue-500'),
('zimsec-g2-math', 'Grade 2 Mathematics', 'ZIMSEC', 'Grade 2', 'N/A', 'Mathematics', 'active', 'Calculator', 'bg-red-500'),
('zimsec-g2-shona', 'Grade 2 Shona', 'ZIMSEC', 'Grade 2', 'N/A', 'Languages', 'active', 'BookOpen', 'bg-blue-600'),
('zimsec-g2-ndebele', 'Grade 2 Ndebele', 'ZIMSEC', 'Grade 2', 'N/A', 'Languages', 'active', 'BookOpen', 'bg-blue-600'),
('zimsec-g2-agriculture', 'Grade 2 Agriculture', 'ZIMSEC', 'Grade 2', 'N/A', 'Sciences', 'active', 'Sprout', 'bg-green-600'),
('zimsec-g2-scitech', 'Grade 2 Science and Technology', 'ZIMSEC', 'Grade 2', 'N/A', 'Sciences', 'active', 'FlaskConical', 'bg-green-500'),
('zimsec-g2-heritage', 'Grade 2 Heritage - Social Studies', 'ZIMSEC', 'Grade 2', 'N/A', 'Humanities', 'active', 'Landmark', 'bg-amber-600'),
('zimsec-g2-fareme', 'Grade 2 FAREME', 'ZIMSEC', 'Grade 2', 'N/A', 'Humanities', 'active', 'Users', 'bg-orange-500'),
('zimsec-g3-english', 'Grade 3 English', 'ZIMSEC', 'Grade 3', 'N/A', 'Languages', 'active', 'BookOpen', 'bg-blue-500'),
('zimsec-g3-math', 'Grade 3 Mathematics', 'ZIMSEC', 'Grade 3', 'N/A', 'Mathematics', 'active', 'Calculator', 'bg-red-500'),
('zimsec-g3-shona', 'Grade 3 Shona', 'ZIMSEC', 'Grade 3', 'N/A', 'Languages', 'active', 'BookOpen', 'bg-blue-600'),
('zimsec-g3-ndebele', 'Grade 3 Ndebele', 'ZIMSEC', 'Grade 3', 'N/A', 'Languages', 'active', 'BookOpen', 'bg-blue-600'),
('zimsec-g3-agriculture', 'Grade 3 Agriculture', 'ZIMSEC', 'Grade 3', 'N/A', 'Sciences', 'active', 'Sprout', 'bg-green-600'),
('zimsec-g3-scitech', 'Grade 3 Science and Technology', 'ZIMSEC', 'Grade 3', 'N/A', 'Sciences', 'active', 'FlaskConical', 'bg-green-500'),
('zimsec-g3-heritage', 'Grade 3 Heritage - Social Studies', 'ZIMSEC', 'Grade 3', 'N/A', 'Humanities', 'active', 'Landmark', 'bg-amber-600'),
('zimsec-g3-fareme', 'Grade 3 FAREME', 'ZIMSEC', 'Grade 3', 'N/A', 'Humanities', 'active', 'Users', 'bg-orange-500'),
('zimsec-g4-english', 'Grade 4 English', 'ZIMSEC', 'Grade 4', 'N/A', 'Languages', 'active', 'BookOpen', 'bg-blue-500'),
('zimsec-g4-math', 'Grade 4 Mathematics', 'ZIMSEC', 'Grade 4', 'N/A', 'Mathematics', 'active', 'Calculator', 'bg-red-500'),
('zimsec-g4-shona', 'Grade 4 Shona', 'ZIMSEC', 'Grade 4', 'N/A', 'Languages', 'active', 'BookOpen', 'bg-blue-600'),
('zimsec-g4-ndebele', 'Grade 4 Ndebele', 'ZIMSEC', 'Grade 4', 'N/A', 'Languages', 'active', 'BookOpen', 'bg-blue-600'),
('zimsec-g4-agriculture', 'Grade 4 Agriculture', 'ZIMSEC', 'Grade 4', 'N/A', 'Sciences', 'active', 'Sprout', 'bg-green-600'),
('zimsec-g4-scitech', 'Grade 4 Science and Technology', 'ZIMSEC', 'Grade 4', 'N/A', 'Sciences', 'active', 'FlaskConical', 'bg-green-500'),
('zimsec-g4-heritage', 'Grade 4 Heritage - Social Studies', 'ZIMSEC', 'Grade 4', 'N/A', 'Humanities', 'active', 'Landmark', 'bg-amber-600'),
('zimsec-g4-fareme', 'Grade 4 FAREME', 'ZIMSEC', 'Grade 4', 'N/A', 'Humanities', 'active', 'Users', 'bg-orange-500'),
('zimsec-g5-english', 'Grade 5 English', 'ZIMSEC', 'Grade 5', 'N/A', 'Languages', 'active', 'BookOpen', 'bg-blue-500'),
('zimsec-g5-math', 'Grade 5 Mathematics', 'ZIMSEC', 'Grade 5', 'N/A', 'Mathematics', 'active', 'Calculator', 'bg-red-500'),
('zimsec-g5-shona', 'Grade 5 Shona', 'ZIMSEC', 'Grade 5', 'N/A', 'Languages', 'active', 'BookOpen', 'bg-blue-600'),
('zimsec-g5-ndebele', 'Grade 5 Ndebele', 'ZIMSEC', 'Grade 5', 'N/A', 'Languages', 'active', 'BookOpen', 'bg-blue-600'),
('zimsec-g5-agriculture', 'Grade 5 Agriculture', 'ZIMSEC', 'Grade 5', 'N/A', 'Sciences', 'active', 'Sprout', 'bg-green-600'),
('zimsec-g5-scitech', 'Grade 5 Science and Technology', 'ZIMSEC', 'Grade 5', 'N/A', 'Sciences', 'active', 'FlaskConical', 'bg-green-500'),
('zimsec-g5-heritage', 'Grade 5 Heritage - Social Studies', 'ZIMSEC', 'Grade 5', 'N/A', 'Humanities', 'active', 'Landmark', 'bg-amber-600'),
('zimsec-g5-fareme', 'Grade 5 FAREME', 'ZIMSEC', 'Grade 5', 'N/A', 'Humanities', 'active', 'Users', 'bg-orange-500'),
('zimsec-g6-english', 'Grade 6 English', 'ZIMSEC', 'Grade 6', 'N/A', 'Languages', 'active', 'BookOpen', 'bg-blue-500'),
('zimsec-g6-math', 'Grade 6 Mathematics', 'ZIMSEC', 'Grade 6', 'N/A', 'Mathematics', 'active', 'Calculator', 'bg-red-500'),
('zimsec-g6-shona', 'Grade 6 Shona', 'ZIMSEC', 'Grade 6', 'N/A', 'Languages', 'active', 'BookOpen', 'bg-blue-600'),
('zimsec-g6-ndebele', 'Grade 6 Ndebele', 'ZIMSEC', 'Grade 6', 'N/A', 'Languages', 'active', 'BookOpen', 'bg-blue-600'),
('zimsec-g6-agriculture', 'Grade 6 Agriculture', 'ZIMSEC', 'Grade 6', 'N/A', 'Sciences', 'active', 'Sprout', 'bg-green-600'),
('zimsec-g6-scitech', 'Grade 6 Science and Technology', 'ZIMSEC', 'Grade 6', 'N/A', 'Sciences', 'active', 'FlaskConical', 'bg-green-500'),
('zimsec-g6-heritage', 'Grade 6 Heritage - Social Studies', 'ZIMSEC', 'Grade 6', 'N/A', 'Humanities', 'active', 'Landmark', 'bg-amber-600'),
('zimsec-g6-fareme', 'Grade 6 FAREME', 'ZIMSEC', 'Grade 6', 'N/A', 'Humanities', 'active', 'Users', 'bg-orange-500'),
('zimsec-g7-english', 'Grade 7 English', 'ZIMSEC', 'Grade 7', 'N/A', 'Languages', 'active', 'BookOpen', 'bg-blue-500'),
('zimsec-g7-math', 'Grade 7 Mathematics', 'ZIMSEC', 'Grade 7', 'N/A', 'Mathematics', 'active', 'Calculator', 'bg-red-500'),
('zimsec-g7-shona', 'Grade 7 Shona', 'ZIMSEC', 'Grade 7', 'N/A', 'Languages', 'active', 'BookOpen', 'bg-blue-600'),
('zimsec-g7-ndebele', 'Grade 7 Ndebele', 'ZIMSEC', 'Grade 7', 'N/A', 'Languages', 'active', 'BookOpen', 'bg-blue-600'),
('zimsec-g7-agriculture', 'Grade 7 Agriculture', 'ZIMSEC', 'Grade 7', 'N/A', 'Sciences', 'active', 'Sprout', 'bg-green-600'),
('zimsec-g7-scitech', 'Grade 7 Science and Technology', 'ZIMSEC', 'Grade 7', 'N/A', 'Sciences', 'active', 'FlaskConical', 'bg-green-500'),
('zimsec-g7-heritage', 'Grade 7 Heritage - Social Studies', 'ZIMSEC', 'Grade 7', 'N/A', 'Humanities', 'active', 'Landmark', 'bg-amber-600'),
('zimsec-g7-fareme', 'Grade 7 FAREME', 'ZIMSEC', 'Grade 7', 'N/A', 'Humanities', 'active', 'Users', 'bg-orange-500'),
('zimsec-f1-math', 'Form 1 Mathematics', 'ZIMSEC', 'Form 1', 'N/A', 'Mathematics', 'active', 'Calculator', 'bg-red-500'),
('zimsec-f1-eng', 'Form 1 English Language', 'ZIMSEC', 'Form 1', 'N/A', 'Languages', 'active', 'BookOpen', 'bg-blue-500'),
('zimsec-f1-combsci', 'Form 1 Combined Science', 'ZIMSEC', 'Form 1', 'N/A', 'Sciences', 'active', 'FlaskConical', 'bg-green-500'),
('zimsec-f1-hist', 'Form 1 History', 'ZIMSEC', 'Form 1', 'N/A', 'Humanities', 'active', 'Landmark', 'bg-amber-500'),
('zimsec-f1-geo', 'Form 1 Geography', 'ZIMSEC', 'Form 1', 'N/A', 'Humanities', 'active', 'Globe', 'bg-teal-500'),
('zimsec-f1-shona', 'Form 1 Shona', 'ZIMSEC', 'Form 1', 'N/A', 'Languages', 'active', 'Book', 'bg-indigo-500'),
('zimsec-f1-ndebele', 'Form 1 Ndebele', 'ZIMSEC', 'Form 1', 'N/A', 'Languages', 'active', 'Book', 'bg-indigo-500'),
('zimsec-f1-acc', 'Form 1 Principles of Accounting', 'ZIMSEC', 'Form 1', 'N/A', 'Humanities', 'active', 'Calculator', 'bg-slate-500'),
('zimsec-f1-com', 'Form 1 Commerce', 'ZIMSEC', 'Form 1', 'N/A', 'Humanities', 'active', 'Briefcase', 'bg-purple-500'),
('zimsec-f1-bio', 'Form 1 Biology', 'ZIMSEC', 'Form 1', 'N/A', 'Sciences', 'active', 'Dna', 'bg-green-600'),
('zimsec-f1-phy', 'Form 1 Physics', 'ZIMSEC', 'Form 1', 'N/A', 'Sciences', 'active', 'Zap', 'bg-yellow-500'),
('zimsec-f1-chem', 'Form 1 Chemistry', 'ZIMSEC', 'Form 1', 'N/A', 'Sciences', 'active', 'FlaskConical', 'bg-emerald-500'),
('zimsec-f1-cs', 'Form 1 Computer Science', 'ZIMSEC', 'Form 1', 'N/A', 'Technology', 'active', 'Monitor', 'bg-cyan-500'),
('zimsec-f1-agri', 'Form 1 Agriculture', 'ZIMSEC', 'Form 1', 'N/A', 'Sciences', 'active', 'Sprout', 'bg-lime-600'),
('zimsec-f2-math', 'Form 2 Mathematics', 'ZIMSEC', 'Form 2', 'N/A', 'Mathematics', 'active', 'Calculator', 'bg-red-500'),
('zimsec-f2-eng', 'Form 2 English Language', 'ZIMSEC', 'Form 2', 'N/A', 'Languages', 'active', 'BookOpen', 'bg-blue-500'),
('zimsec-f2-combsci', 'Form 2 Combined Science', 'ZIMSEC', 'Form 2', 'N/A', 'Sciences', 'active', 'FlaskConical', 'bg-green-500'),
('zimsec-f2-hist', 'Form 2 History', 'ZIMSEC', 'Form 2', 'N/A', 'Humanities', 'active', 'Landmark', 'bg-amber-500'),
('zimsec-f2-geo', 'Form 2 Geography', 'ZIMSEC', 'Form 2', 'N/A', 'Humanities', 'active', 'Globe', 'bg-teal-500'),
('zimsec-f2-shona', 'Form 2 Shona', 'ZIMSEC', 'Form 2', 'N/A', 'Languages', 'active', 'Book', 'bg-indigo-500'),
('zimsec-f2-ndebele', 'Form 2 Ndebele', 'ZIMSEC', 'Form 2', 'N/A', 'Languages', 'active', 'Book', 'bg-indigo-500'),
('zimsec-f2-acc', 'Form 2 Principles of Accounting', 'ZIMSEC', 'Form 2', 'N/A', 'Humanities', 'active', 'Calculator', 'bg-slate-500'),
('zimsec-f2-com', 'Form 2 Commerce', 'ZIMSEC', 'Form 2', 'N/A', 'Humanities', 'active', 'Briefcase', 'bg-purple-500'),
('zimsec-f2-bio', 'Form 2 Biology', 'ZIMSEC', 'Form 2', 'N/A', 'Sciences', 'active', 'Dna', 'bg-green-600'),
('zimsec-f2-phy', 'Form 2 Physics', 'ZIMSEC', 'Form 2', 'N/A', 'Sciences', 'active', 'Zap', 'bg-yellow-500'),
('zimsec-f2-chem', 'Form 2 Chemistry', 'ZIMSEC', 'Form 2', 'N/A', 'Sciences', 'active', 'FlaskConical', 'bg-emerald-500'),
('zimsec-f2-cs', 'Form 2 Computer Science', 'ZIMSEC', 'Form 2', 'N/A', 'Technology', 'active', 'Monitor', 'bg-cyan-500'),
('zimsec-f2-agri', 'Form 2 Agriculture', 'ZIMSEC', 'Form 2', 'N/A', 'Sciences', 'active', 'Sprout', 'bg-lime-600'),
('zimsec-f3-math', 'Form 3 Mathematics', 'ZIMSEC', 'Form 3', '4004', 'Mathematics', 'active', 'Calculator', 'bg-red-500'),
('zimsec-f3-eng', 'Form 3 English Language', 'ZIMSEC', 'Form 3', '1122', 'Languages', 'active', 'BookOpen', 'bg-blue-500'),
('zimsec-f3-combsci', 'Form 3 Combined Science', 'ZIMSEC', 'Form 3', '4003', 'Sciences', 'active', 'FlaskConical', 'bg-green-500'),
('zimsec-f3-hist', 'Form 3 History', 'ZIMSEC', 'Form 3', '2167', 'Humanities', 'active', 'Landmark', 'bg-amber-500'),
('zimsec-f3-geo', 'Form 3 Geography', 'ZIMSEC', 'Form 3', '2248', 'Humanities', 'active', 'Globe', 'bg-teal-500'),
('zimsec-f3-shona', 'Form 3 Shona', 'ZIMSEC', 'Form 3', '3159', 'Languages', 'active', 'Book', 'bg-indigo-500'),
('zimsec-f3-ndebele', 'Form 3 Ndebele', 'ZIMSEC', 'Form 3', '3167', 'Languages', 'active', 'Book', 'bg-indigo-500'),
('zimsec-f3-acc', 'Form 3 Principles of Accounting', 'ZIMSEC', 'Form 3', '7112', 'Humanities', 'active', 'Calculator', 'bg-slate-500'),
('zimsec-f3-com', 'Form 3 Commerce', 'ZIMSEC', 'Form 3', '7103', 'Humanities', 'active', 'Briefcase', 'bg-purple-500'),
('zimsec-f3-bio', 'Form 3 Biology', 'ZIMSEC', 'Form 3', '4005', 'Sciences', 'active', 'Dna', 'bg-green-600'),
('zimsec-f3-phy', 'Form 3 Physics', 'ZIMSEC', 'Form 3', '4006', 'Sciences', 'active', 'Zap', 'bg-yellow-500'),
('zimsec-f3-chem', 'Form 3 Chemistry', 'ZIMSEC', 'Form 3', '4007', 'Sciences', 'active', 'FlaskConical', 'bg-emerald-500'),
('zimsec-f3-cs', 'Form 3 Computer Science', 'ZIMSEC', 'Form 3', '4021', 'Technology', 'active', 'Monitor', 'bg-cyan-500'),
('zimsec-f3-agri', 'Form 3 Agriculture', 'ZIMSEC', 'Form 3', '5034', 'Sciences', 'active', 'Sprout', 'bg-lime-600'),
('zimsec-f4-math', 'Form 4 Mathematics', 'ZIMSEC', 'Form 4', '4004', 'Mathematics', 'active', 'Calculator', 'bg-red-500'),
('zimsec-f4-eng', 'Form 4 English Language', 'ZIMSEC', 'Form 4', '1122', 'Languages', 'active', 'BookOpen', 'bg-blue-500'),
('zimsec-f4-combsci', 'Form 4 Combined Science', 'ZIMSEC', 'Form 4', '4003', 'Sciences', 'active', 'FlaskConical', 'bg-green-500'),
('zimsec-f4-hist', 'Form 4 History', 'ZIMSEC', 'Form 4', '2167', 'Humanities', 'active', 'Landmark', 'bg-amber-500'),
('zimsec-f4-geo', 'Form 4 Geography', 'ZIMSEC', 'Form 4', '2248', 'Humanities', 'active', 'Globe', 'bg-teal-500'),
('zimsec-f4-shona', 'Form 4 Shona', 'ZIMSEC', 'Form 4', '3159', 'Languages', 'active', 'Book', 'bg-indigo-500'),
('zimsec-f4-ndebele', 'Form 4 Ndebele', 'ZIMSEC', 'Form 4', '3167', 'Languages', 'active', 'Book', 'bg-indigo-500'),
('zimsec-f4-acc', 'Form 4 Principles of Accounting', 'ZIMSEC', 'Form 4', '7112', 'Humanities', 'active', 'Calculator', 'bg-slate-500'),
('zimsec-f4-com', 'Form 4 Commerce', 'ZIMSEC', 'Form 4', '7103', 'Humanities', 'active', 'Briefcase', 'bg-purple-500'),
('zimsec-f4-bio', 'Form 4 Biology', 'ZIMSEC', 'Form 4', '4005', 'Sciences', 'active', 'Dna', 'bg-green-600'),
('zimsec-f4-phy', 'Form 4 Physics', 'ZIMSEC', 'Form 4', '4006', 'Sciences', 'active', 'Zap', 'bg-yellow-500'),
('zimsec-f4-chem', 'Form 4 Chemistry', 'ZIMSEC', 'Form 4', '4007', 'Sciences', 'active', 'FlaskConical', 'bg-emerald-500'),
('zimsec-f4-cs', 'Form 4 Computer Science', 'ZIMSEC', 'Form 4', '4021', 'Technology', 'active', 'Monitor', 'bg-cyan-500'),
('zimsec-f4-agri', 'Form 4 Agriculture', 'ZIMSEC', 'Form 4', '5034', 'Sciences', 'active', 'Sprout', 'bg-lime-600'),
('zimsec-f5-math', 'Form 5 Pure Mathematics', 'ZIMSEC', 'Form 5', '6042', 'Mathematics', 'active', 'Calculator', 'bg-red-500'),
('zimsec-f5-stat', 'Form 5 Statistics', 'ZIMSEC', 'Form 5', '6043', 'Mathematics', 'active', 'LineChart', 'bg-red-600'),
('zimsec-f5-bio', 'Form 5 Biology', 'ZIMSEC', 'Form 5', '6030', 'Sciences', 'active', 'Dna', 'bg-green-500'),
('zimsec-f5-chem', 'Form 5 Chemistry', 'ZIMSEC', 'Form 5', '6032', 'Sciences', 'active', 'FlaskConical', 'bg-emerald-500'),
('zimsec-f5-phy', 'Form 5 Physics', 'ZIMSEC', 'Form 5', '6031', 'Sciences', 'active', 'Zap', 'bg-yellow-500'),
('zimsec-f5-acc', 'Form 5 Accounting', 'ZIMSEC', 'Form 5', '6001', 'Humanities', 'active', 'Calculator', 'bg-slate-500'),
('zimsec-f5-bus', 'Form 5 Business Enterprise', 'ZIMSEC', 'Form 5', '6004', 'Humanities', 'active', 'Briefcase', 'bg-purple-500'),
('zimsec-f5-eco', 'Form 5 Economics', 'ZIMSEC', 'Form 5', '6008', 'Humanities', 'active', 'LineChart', 'bg-purple-600'),
('zimsec-f5-geo', 'Form 5 Geography', 'ZIMSEC', 'Form 5', '6016', 'Humanities', 'active', 'Globe', 'bg-teal-500'),
('zimsec-f5-hist', 'Form 5 History', 'ZIMSEC', 'Form 5', '6021', 'Humanities', 'active', 'Landmark', 'bg-amber-500'),
('zimsec-f5-cs', 'Form 5 Computer Science', 'ZIMSEC', 'Form 5', '6023', 'Technology', 'active', 'Monitor', 'bg-cyan-500'),
('zimsec-f5-lit', 'Form 5 Literature in English', 'ZIMSEC', 'Form 5', '6015', 'Languages', 'active', 'Book', 'bg-indigo-500'),
('zimsec-f5-shona', 'Form 5 Shona', 'ZIMSEC', 'Form 5', '6011', 'Languages', 'active', 'BookOpen', 'bg-blue-600'),
('zimsec-f5-ndebele', 'Form 5 Ndebele', 'ZIMSEC', 'Form 5', '6012', 'Languages', 'active', 'BookOpen', 'bg-blue-600'),
('zimsec-f6-math', 'Form 6 Pure Mathematics', 'ZIMSEC', 'Form 6', '6042', 'Mathematics', 'active', 'Calculator', 'bg-red-500'),
('zimsec-f6-stat', 'Form 6 Statistics', 'ZIMSEC', 'Form 6', '6043', 'Mathematics', 'active', 'LineChart', 'bg-red-600'),
('zimsec-f6-bio', 'Form 6 Biology', 'ZIMSEC', 'Form 6', '6030', 'Sciences', 'active', 'Dna', 'bg-green-500'),
('zimsec-f6-chem', 'Form 6 Chemistry', 'ZIMSEC', 'Form 6', '6032', 'Sciences', 'active', 'FlaskConical', 'bg-emerald-500'),
('zimsec-f6-phy', 'Form 6 Physics', 'ZIMSEC', 'Form 6', '6031', 'Sciences', 'active', 'Zap', 'bg-yellow-500'),
('zimsec-f6-acc', 'Form 6 Accounting', 'ZIMSEC', 'Form 6', '6001', 'Humanities', 'active', 'Calculator', 'bg-slate-500'),
('zimsec-f6-bus', 'Form 6 Business Enterprise', 'ZIMSEC', 'Form 6', '6004', 'Humanities', 'active', 'Briefcase', 'bg-purple-500'),
('zimsec-f6-eco', 'Form 6 Economics', 'ZIMSEC', 'Form 6', '6008', 'Humanities', 'active', 'LineChart', 'bg-purple-600'),
('zimsec-f6-geo', 'Form 6 Geography', 'ZIMSEC', 'Form 6', '6016', 'Humanities', 'active', 'Globe', 'bg-teal-500'),
('zimsec-f6-hist', 'Form 6 History', 'ZIMSEC', 'Form 6', '6021', 'Humanities', 'active', 'Landmark', 'bg-amber-500'),
('zimsec-f6-cs', 'Form 6 Computer Science', 'ZIMSEC', 'Form 6', '6023', 'Technology', 'active', 'Monitor', 'bg-cyan-500'),
('zimsec-f6-lit', 'Form 6 Literature in English', 'ZIMSEC', 'Form 6', '6015', 'Languages', 'active', 'Book', 'bg-indigo-500'),
('zimsec-f6-shona', 'Form 6 Shona', 'ZIMSEC', 'Form 6', '6011', 'Languages', 'active', 'BookOpen', 'bg-blue-600'),
('zimsec-f6-ndebele', 'Form 6 Ndebele', 'ZIMSEC', 'Form 6', '6012', 'Languages', 'active', 'BookOpen', 'bg-blue-600');